import peticom_logo from "../svg/others/logo.svg";
import cat from "../svg/badges/cat.svg";
import dog from "../svg/badges/dog.svg";
import handshake from "../svg/badges/handshake-with-heart.svg";
import none_dog from "../svg/badges/none-dog.svg";
import smiley_face from "../svg/badges/smiley-face.svg";
import smoke_free from "../svg/badges/smoke-free.svg";
import car from "../svg/badges/car.svg";
import car_distance from "../svg/badges/car-distance.svg";
import garden from "../svg/badges/garden.svg";

export const PeticomLogo = peticom_logo;
export const Cat = cat;
export const Dog = dog;
export const Handshake = handshake;
export const NoneDog = none_dog;
export const SmileyFace = smiley_face;
export const SmokeFree = smoke_free;
export const Car = car;
export const CarDistance = car_distance;
export const Garden = garden;